config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome' => 'welcome#index'
  root 'welcome#index'
  
  post 'allpay/result'
  post 'allpay/return'
  get  'allpay/final'

  resources :products do
    collection do
      post :bulk_update
      post :bulk_delete
    end
    resources :packets
    resource :detail, :controller => "product_details"
  end

  resources :orders do
    get :checkout, :on => :member
  end

  resources :abouts
  resource :cart

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :products
    resources :orders
    resources :abouts

    resources :users #假設要修改user資料 PATCH /api/v1/users/1234
    
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  validates_presence_of :name
  has_many :line_items, :dependent => :destroy
  has_many :trades, :dependent => :destroy
  has_many :products, through: :line_items
  belongs_to :user

  def self.new_from_cart cart, params = {}
    order = self.new params
    order.line_items = cart.line_items
    order
  end

  def paid?
    trades.exists?(paid: true)
  end

  def total
    line_items.sum(:subtotal)
  end

end

app/controllers/api_v1/orders_controller.rb
class ApiV1::OrdersController < ApiController

  def create
    @order = Order.new( name: params[:name],
                        phone: params[:phone],
                        address: params[:address],
                        email: params[:email],                       
                        payment_method: params[:payment_method], 
                        amount: params[:amount] )

    Array(params[:line_items]).each do |line_item|
      @order.line_items.build( :product_id => line_item[:product_id],
                               :packet_id => line_item[:packet_id],
                               :subtotal => line_item[:subtotal],
                               :qty => line_item[:qty] )
    end

    if current_user
      @order.user = current_user
    else
      user = User.find_by_email( @order.email )
      @order.user = user
    end

    if  @order.save
        render :json => { :message => "OK", :order_id => @order.id, :pay_url => checkout_order_url(@order) }
    else
        render :json => { :errors => @order.errors.full_messages }, :status => 400
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :authenticate_user!, :except => :checkout
  before_action :check_admin, :except => :checkout

  def index
    @orders = Order.includes(:user).page(params[:page]).per(7)
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_url
  end

  def create
    @order = Order.new_from_cart current_cart, order_params
    if @order.save
      current_cart.clear
      redirect_to @order
    else
      render :new
    end
  end

  def checkout    
    order = Order.find params[:id]
    if order.paid?
      redirect_to order, alert: '已經付過款'
    else

      return_url = if Rails.env.production?
        "http://www.inseason.tw/allpay/return"
      else
        'http://requestb.in/14x3b9x1'
      end

      trade = order.trades.create!
      allpay = Allpay.new
      @checkout_params = {
        MerchantID: allpay.merchant_id,
        MerchantTradeNo: trade.trade_number,
        MerchantTradeDate: Time.now.strftime('%Y/%m/%d %H:%M:%S'),
        PaymentType: :aio,
        TotalAmount: order.total.round,
        TradeDesc: :'My Cart',
        ItemName: order.line_items.map{ |i| "#{i.product.name} x #{i.qty}" }.join('#'),
        ChoosePayment: order.payment_method,
        ReturnURL: return_url,
        OrderResultURL: allpay_result_url
      }
      @checkout_params[:CheckMacValue] = allpay.make_mac(@checkout_params)

      render :layout => "simple"
    end
  end

  private

  def order_params
    params.require(:order).permit(:name, :address, :payment_method, :phone, :email)
  end

end

app/helpers/api_v1/orders_helper.rb
module ApiV1::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/checkout.html.erb
<h1>處理中</h1>
<form action="http://payment-stage.allpay.com.tw/Cashier/AioCheckOut"
 method="post"
 style="display:none">
 <% @checkout_params.each do |name, value| %>
 <%= hidden_field_tag name, value %>
 <% end %>
 <input type="submit">
</form>
<script>document.forms[0].submit()</script>

app/views/orders/index.html.erb
<table class="table table-bordered order-index">
  <% @orders.each do |o| %>
  <tr>
    <td>使用者</td>
    <td>收件人</td>
    <td>訂單編號</td>
    <td>聯絡電話</td>
    <td></td>
    <td>建立時間</td>
  </tr>

    <tr>
      <td>
        <% if o.user %>
          <%= o.user.id %>
          <%= o.user.name %>
        <% end %>
      </td>
      <td>
        <%= o.name %>
      </td>
      <td>
        <% o.trades.each do |t| %>
          <%= t.trade_number %> 
        <% end %>
      </td>
      <td>
        <%= o.phone %>
      </td>
      <td>
      <%= link_to "詳細", order_path(o), :class => "btn btn-primary" %>
      <%= link_to "刪除", order_path(o), :method => "delete", :class => "btn btn-danger" %>
      </td>
      <td>
        <%= o.created_at.to_s(:short) %>
      </td>
    </tr>
  <% end %>
  </table>
  <%= paginate @orders %>

app/views/orders/new.html.erb
<h1>建立訂單</h1>

<%= form_for @order do |f| %>
  <%= f.text_field :name, placeholder: 'NAME' %>
  <%= f.text_field :address, placeholder: 'ADDRESS' %>
  <%= f.select :payment_method, %w[Credit ATM] %>
  <%= f.submit %>
<% end %>

app/views/orders/show.html.erb
<h2>訂單 NO.<%= @order.id %></h2>

<%#= link_to '結帳', checkout_order_path(@order) %>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">訂單明細</div>

  <!-- Table -->
  <table class="table">
   <thead>
    <tr>
      <th width="20%">產品</th><th width="10%">單位價</th> <th width="10%">數量</th><th width="10%">小計</th>
    </tr>
  </thead>
  <tbody>
    <% @order.line_items.each do |line_item| %>
      <tr>
        <td><%= link_to line_item.product.name, product_path(line_item.product) %></td>
        <td>$<%= line_item.subtotal %></td>
        <td><%= line_item.qty %></td>
        <td>$<%= line_item.amount %></td>
      </tr>
      <% if line_item.packet %>
      <tr>
        <td colspan="2">     <%= link_to line_item.packet.title, product_packet_path(line_item.product, line_item.packet) %></td>
        <td colspan="2"></td>
      </tr>
      <% end %>
    <% end %>
    <tr>
      <td width="10%">訂購人:  <%= @order.name %></td><td width="10%">聯絡電話:  <%= @order.phone %></td> <td width="10%">付款方式:  <%= @order.payment_method %></td><td width="10%"></td>
    </tr>
    <tr>
      <td width="10%">地址:  <%= @order.address %></td><td width="10%">Email:  <%= @order.email %></td> <td width="10%"></td><td width="10%"></td>
    </tr>
    <tr>
      <td colspan="2"></td>
      <td><b>總計</b></td>
      <td>NT. $<%= @order.total %></td>
    </tr>
  </tbody>
  </table>
</div>

<h3>交易紀錄</h3>
<div class="order-history">
  <ul>
    <% @order.trades.each do |trade| %>
    <li><%= trade.paid? ? icon("bell") : icon("remove") %> <%= trade.trade_number %> <%= trade.paid? ? :已付款 : :未付款 %></li>
    <% end %>
  </ul>
</div>