config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome' => 'welcome#index'
  root 'welcome#index'
  
  post 'allpay/result'
  post 'allpay/return'
  get  'allpay/final'

  resources :products do
    collection do
      post :bulk_update
      post :bulk_delete
    end
    resources :packets
    resource :detail, :controller => "product_details"
  end

  resources :orders do
    get :checkout, :on => :member
  end

  resources :abouts
  resource :cart

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :products
    resources :orders
    resources :abouts

    resources :users #假設要修改user資料 PATCH /api/v1/users/1234
    
  end

end

app/models/packet.rb
class Packet < ActiveRecord::Base
  validates_presence_of :title, :product_id
  belongs_to :product

  has_many :pictures, :as => :imageable

  accepts_nested_attributes_for :pictures, allow_destroy: true, :reject_if => :all_blank

  def final_price
    self.price + self.product.price    
  end
  
end

app/controllers/packets_controller.rb
class PacketsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_product
  before_action :check_admin

  def index
    @packets = @product.packets
  end

  def show
    @packet = @product.packets.find( params[:id] )
  end

  def new
    @packet = @product.packets.build
    @packet.pictures.build if @packet.pictures.empty?
  end

  def create
    @packet = @product.packets.build( packet_params )

    if @packet.save
      redirect_to product_packets_path(@product)
    else
      render :new
    end
  end

  def edit
    @packet = @product.packets.find( params[:id] )
    @packet.pictures.build if @packet.pictures.empty?

  end

  def update
    
    @packet = @product.packets.find( params[:id] )

    if @packet.update( packet_params )
      redirect_to product_packets_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @packet = @product.packets.find( params[:id] )

    @packet.destroy

    redirect_to product_packets_path(@product)
  end

  protected

  def packet_params
    params.require(:packet).permit(:title, :content, :price, :video, :ingredient, :pictures_attributes => [:id, :title, :image, :_destroy] )
  end

  def set_product
    @product = Product.find(params[:product_id])  
  end
end

app/helpers/packets_helper.rb
module PacketsHelper
end

app/views/packets/_form.html.erb
<% if @packet.errors.any? %>
      <ul>
      <% @packet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>
  <%= f.label "名稱" %>
  <%= f.text_field :title, :size => "40" %>
  <%= f.label "價格" %>
  <%= f.text_field :price, :size => "10"  %>
<br>
  <h5>內容</h5>
  <%= f.text_area :content, :size => "60x10", :class => "vertical-base"%>
<br>
  <h5>配料</h5>
  <%= f.text_area :ingredient, :size => "60x10", :class => "vertical-base"%>
<br>
  <%= f.label "影片" %>
  <%= f.text_field :video, :size => "55" %>
<p>
<br>
<%= f.add_nested_fields_link :pictures, "新增圖片", :class => "btn btn-xs btn-success"  %>
<%= f.nested_fields_for :pictures do |ff| %>
    <%= f.label "圖片" %>   
    <%= ff.text_field :title %>
    <span><%= ff.remove_nested_fields_link "" , :class => "glyphicon glyphicon-remove" %></span>
    <%= ff.file_field :image %>   
<% end %>
</p>


<br>
<%= link_to "回料理包列表", product_packets_path(@product), :class => "btn btn-info" %>
<%= f.submit "送出", :class => "btn btn-primary" %>

app/views/packets/edit.html.erb
<%= form_for @packet, :url => product_packet_path(@product, @packet), :method => :patch do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

<% end %>

app/views/packets/index.html.erb
<h2><%= @product.name %> 料理包</h2>

<table class="table table-striped">
  <% @packets.each do |a| %>
    <tr>
      <td><%= a.title %></td>
      <td>$<%= a.price %></td>
      <td>

        <%= link_to "預覽", product_packet_path(@product, a), :class => "btn btn-info" %>

        <%= link_to "編輯", edit_product_packet_path(@product, a), :class => "btn btn-default" %>

        <%= link_to "刪除", product_packet_path(@product, a), :method => "delete", :class => "btn btn-danger" %>

      </td>
    </tr>
  <% end %>
</table>
<%= link_to "回產品列表", products_path(@product), :class => "btn btn-info"%>
<%= link_to "新增", new_product_packet_path(@product), :class => "btn btn-primary" %>

app/views/packets/new.html.erb
<%= form_for @packet, :url => product_packets_path(@product) do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

<% end %>

app/views/packets/show.html.erb
<h2><%= @packet.title %>料理包</h2>
<table class="table" >
  <tr>
    <td width="10%">介紹:</td>
    <td width="60%"><%= @packet.content %></td>
  </tr>
  <tr>
    <td>價錢: </td>
    <td><%= @packet.price %></td>
  </tr>
  <tr>
    <td>影片網址:</td>
    <td><%= @packet.video %></td>
  </tr>
  <tr>
    <td>配料描述: </td>
    <td><%= @packet.ingredient %></td>
  </tr>
  <tr>
    <td>圖片</td>
    <td><% @packet.pictures.each do |p| %>
        <p>
        <%= p.title %>
        <%= image_tag p.image(:medium) %>
        </p>
        <% end %>
    </td>
  </tr>
</table>

<%= link_to "回料理包列表", product_packets_path(@product), :class => "btn btn-info"%>