config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome' => 'welcome#index'
  root 'welcome#index'
  
  post 'allpay/result'
  post 'allpay/return'
  get  'allpay/final'

  resources :products do
    collection do
      post :bulk_update
      post :bulk_delete
    end
    resources :packets
    resource :detail, :controller => "product_details"
  end

  resources :orders do
    get :checkout, :on => :member
  end

  resources :abouts
  resource :cart

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :products
    resources :orders
    resources :abouts

    resources :users #假設要修改user資料 PATCH /api/v1/users/1234
    
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :packets, :dependent => :destroy
  has_many :line_items

  belongs_to :user

  STATUS = ["published", "draft"]
  validates_presence_of :name, :price, :in_stock_qty
  validates_numericality_of :in_stock_qty, :only_integer => true
  validates_numericality_of :price, :only_integer => true, :greater_than => 1

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def rating
    rand(30)
  end
  
  def self.only_published(u)
    where( ["status = ? OR ( status = ? AND user_id = ? )", "published", "draft", u.id ] )
  end
end

app/controllers/api_v1/products_controller.rb
class ApiV1::ProductsController < ApiController

  def index
    @products = Product.where(:status => "published").includes(:packets => :pictures).all
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin

  def index

    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true).page(params[:page]).per(7)

  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
  @product = Product.new( product_params )

    if @product.save

      flash[:notice] = "新增成功"

      redirect_to products_path
    else
      load_products
      render :action => :index
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update( product_params )

      flash[:notice] = "編輯成功"

      redirect_to products_path
    else
      render :action => :edit
    end
  end

  def bulk_update
    products = params[:ids].map{ |x| Product.find(x) }

    products.each do |x|
      if params["btn-delete"]
        x.destroy
      elsif params["btn-publish"]
        x.update( :status => "published" )
      end
    end

    redirect_to products_url
  end

  def bulk_delete
    Product.first.destroy

    flash[:alert] = "刪除成功"
    redirect_to products_url
  end

  protected

  def product_params
    params.require(:product).permit(:name, :image, :description, :price, :status,:in_stock_qty)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<% if @product.errors.any? %>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

  <%= f.label "產品名" %>
  <%= f.text_field :name, :size => "30" %>
<br>
  <h5>介紹</h5>
  <%= f.text_area :description, :size => "50x10"%>
<br>  
  <%= f.label "價格" %>
  <%= f.text_field :price ,:size => "8"%>
  <%= f.label "庫存數" %>
  <%= f.text_field :in_stock_qty, :size => "4" %>
<br>
<div class="form-group">
  <%= f.label :status, "狀態" %>
  <%= f.select :status, product_status_options %>
</div>

<div class="form-group">
  <%= f.label :image, "產品圖片" %>
  <%= f.file_field :image %>
  
</div>


  <%= f.submit "送出", :class => "btn btn-primary" %>

app/views/products/edit.html.erb
<div class="about">
<%= form_for @product, :url => product_path(@product), :method => :patch do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

<% end %>
</div>

app/views/products/index.html.erb
<%= search_form_for @q do |f| %>
<%= link_to "新增產品", new_product_path(@product), :class => "btn btn-primary" %>
    <div class="row">

      <div class=" col-xs-4 col-lg-4 no-padding">
        <%= f.search_field :name_cont , :class => "form-control", :placeholder => "Search"%>
      </div>
      <div class=" col-xs-4 col-lg-4 no-padding">
      <%= f.submit :class => "btn btn-default" %>
      </div>  
    </div>
<% end %>


<div class="rank">
<%= sort_link(@q, :created_at, "建立時間", default_order: :desc) %>
<%= sort_link(@q, :price, "價格", default_order: :desc) %>
</div>
<%= form_tag bulk_update_products_path do %>
  <table class="table table-striped">
  <tr>
    <th>產品名</th>
    <th>圖片</th>
    <th>價格</th>
    <th>內容</th>
    <th>建立時間</th>
  </tr>
  <% @products.each do |e| %>
    <tr>
      <td class="<%= e.status %>">
        <%= check_box_tag "ids[]", e.id, false %> 
        <%= e.name %>
      </td>
      <td>
        <%= image_tag( e.image(:thumb) ) %>
      </td>
      <td>  
        $<%= e.price %>
      </td>
      <td>
        <%= link_to "顯示", product_path(e), :class => "btn btn-info" %>
        <%= link_to "料理包", product_packets_path(e), :class => "btn btn-warning" %>
        <%= link_to "編輯", edit_product_path(e), :class => "btn btn-default" %>
      </td>
      <td>
        <%= e.created_at.to_s(:short) %>
      </td>
    </tr>
  <% end %>
  </table>
  <%= submit_tag "刪除", :name => "btn-delete", :class => "btn btn-danger" %>
  <%=submit_tag "發佈", :name => "btn-publish", :class => "btn btn-success" %>
<% end %>

<%= paginate @products %>

app/views/products/new.html.erb
<%= form_for @product,:html => {:class => 'form-horizontal'}, :url => products_path(@product) do |f| %>

  <%= render :partial => "form", :locals => { :f => f } %>

<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>


<h3>$<%= @product.price %></h3>

<p style="width: 60%;">
<%= @product.description %>
</p>

<% if @product.image.exists? %> 
   <%= image_tag @product.image(:medium) %>
<%end %>