config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'welcome' => 'welcome#index'
  root 'welcome#index'
  
  post 'allpay/result'
  post 'allpay/return'
  get  'allpay/final'

  resources :products do
    collection do
      post :bulk_update
      post :bulk_delete
    end
    resources :packets
    resource :detail, :controller => "product_details"
  end

  resources :orders do
    get :checkout, :on => :member
  end

  resources :abouts
  resource :cart

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :products
    resources :orders
    resources :abouts

    resources :users #假設要修改user資料 PATCH /api/v1/users/1234
    
  end

end

app/models/about.rb
class About < ActiveRecord::Base
  belongs_to :user
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  has_many :line_items
  
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  validates_presence_of :product

  belongs_to :product # product_id
  belongs_to :packet # packet_id
  
  belongs_to :cart
  belongs_to :order

  before_validation :setup_subtotal

  def amount
    if self.packet
      self.qty * self.packet.final_price
    else      
      self.qty * self.product.price
    end
  end

  protected

  def setup_subtotal
    self.subtotal = amount
  end

end

app/models/order.rb
class Order < ActiveRecord::Base

  validates_presence_of :name
  has_many :line_items, :dependent => :destroy
  has_many :trades, :dependent => :destroy
  has_many :products, through: :line_items
  belongs_to :user

  def self.new_from_cart cart, params = {}
    order = self.new params
    order.line_items = cart.line_items
    order
  end

  def paid?
    trades.exists?(paid: true)
  end

  def total
    line_items.sum(:subtotal)
  end

end

app/models/packet.rb
class Packet < ActiveRecord::Base
  validates_presence_of :title, :product_id
  belongs_to :product

  has_many :pictures, :as => :imageable

  accepts_nested_attributes_for :pictures, allow_destroy: true, :reject_if => :all_blank

  def final_price
    self.price + self.product.price    
  end
  
end

app/models/picture.rb
class Picture < ActiveRecord::Base

  belongs_to :imageable, :polymorphic => true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :packets, :dependent => :destroy
  has_many :line_items

  belongs_to :user

  STATUS = ["published", "draft"]
  validates_presence_of :name, :price, :in_stock_qty
  validates_numericality_of :in_stock_qty, :only_integer => true
  validates_numericality_of :price, :only_integer => true, :greater_than => 1

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def rating
    rand(30)
  end
  
  def self.only_published(u)
    where( ["status = ? OR ( status = ? AND user_id = ? )", "published", "draft", u.id ] )
  end
end

app/models/trade.rb
require 'allpay'
class Trade < ActiveRecord::Base
  serialize :params, JSON
  belongs_to :order
  validate :check_mac, on: :update
  after_initialize :generate_trade_number, if: :new_record?

  def self.find_and_initialize_by_allpay params = {}
    trade = self.find_by(trade_number: params[:MerchantTradeNo])
    trade.paid = params['RtnCode'] == '1'
    trade.params = params
    trade
  end

private

  def check_mac
    allpay = Allpay.new
    errors.add(:params, 'wrong mac value') unless allpay.check_mac(params)
  end

  def generate_trade_number
    self.trade_number = SecureRandom.hex(3)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :orders
  
  before_save :ensure_authentication_token
  
  def admin?
    self.role == "admin"
  end

  def self.get_facebook_user_data(access_token)
    conn = Faraday.new(:url => 'https://graph.facebook.com/me')
    response = conn.get "/me", { :access_token => access_token }
    data = JSON.parse(response.body)

    if response.status == 200
      data
    else
      Rails.logger.warn(data)
      nil
    end
  end

  def self.from_omniauth(auth)
    user = where( fb_uid: auth.uid ).first

    unless user
      user = self.new
      user.fb_uid = auth.uid
      user.email = auth.info.email
      user.image = auth.info.image
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end

    if auth.credentials
      user.fb_access_token = auth.credentials.token
      user.fb_expires_at = Time.at(auth.credentials.expires_at)
    end

    user.save
    user
  end

  # 從 Facebook 認證回來時，如果該 fb_uid 不存在
  # self.from_omniauth 會試圖直接新增 User
  # 如果新增失敗(例如有其他 validation 不過)，devise 就會導去註冊頁面
  # 而 self.new_with_session 這個方法提供註冊頁面的預設值
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def generate_authentication_token
    token = nil

    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end

    self.authentication_token = token
  end

  protected

  def ensure_authentication_token
    if authentication_token.blank?
      self.authentication_token = generate_authentication_token
    end
  end

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  before_action :authenticate_user!
  before_action :check_admin

  def index
    @abouts = About.all
  end

  def show
    @about = About.find(params[:id])
  end

  def new
    @about = About.new
  end

  def create
    @about = About.new( about_params )

    if @about.save
      flash[:notice] = "新增成功"

      redirect_to abouts_path
    else
      render :action => :index
    end

  end

  def edit
    @about = About.first
  end

  def update
    @about = About.first

    if @about.update( about_params )

      flash[:notice] = "編輯成功"

      redirect_to edit_about_path
    else
      render :action => :edit
    end
  end


  protected

  def about_params
    params.require(:about).permit(:title, :content, :phone, :email, :atm_account)
  end
end

app/controllers/allpay_controller.rb
require 'allpay'
class AllpayController < ApplicationController
  skip_before_action :verify_authenticity_token
  
  before_action :set_trade, :except => :final

  def result
    if @trade.save
      redirect_to allpay_final_path, alert: '交易成功'
    else
      redirect_to allpay_final_path, alert: '交易失敗'
    end
  end

  def final
    render :layout => "simple"
  end

  def return
    if @trade.save
      render text: :'1|OK'
    else
     render text: :'0|ErrorMessage'
    end
  end  

private

  def set_trade
    @trade = Trade.find_and_initialize_by_allpay(request.POST)
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base

  before_action :authenticate_user_from_token!

  protected

  def authenticate_user_from_token!
    if params[:auth_token].present?
      user = User.find_by_authentication_token(params[:auth_token])

      if user
        sign_in user, store: false
      end
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def create
    product = Product.find(params[:product_id])
    line_item = current_cart.add_line_item(product)
    line_item.save!

    redirect_to :back
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(name)
    "<span class=\"glyphicon glyphicon-#{name}\"><span>".html_safe
  end
  def product_status_options
    # [ ["發布","published"], ["草稿", "draft"] ]

    Product::STATUS.map{ |s| [ t(s, :scope => "product"), s] }
    #Event::STATUS.map{ |s| [ t( "event.#{s}" ), s] }
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/packets_helper.rb
module PacketsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inseason</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if Rails.env.prodcution? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  // ga('create', 'UA-145330-19', 'auto');
  ga('send', 'pageview');
</script>
<% end %>
<div class="main">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%=link_to(image_tag("logo.png", alt: "Edit Entry"), products_path)  %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <% if current_user %>
            <p class="navbar-text ">
            Hi!<%= current_user.name || current_user.email%>
            <%= image_tag current_user.image %>
            <%= link_to('修改密碼', edit_registration_path(:user)) %> |           
            <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
            </p>
            
            <% else %>
            <div class="navbar-text login-top">
            <%= link_to('註冊', new_registration_path(:user)) %> |
            <%= link_to('登入', new_session_path(:user)) %>   
            <%#= link_to "Facebook 登入", user_omniauth_authorize_path(:facebook) %></div>
           
  
            <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div> 
  <div id="main-container" class="container">
      <div class="row">

        <div id="content" class="col-xs-12">

          <% if flash[:notice] %>
            <div class="alert alert-success"><%= flash[:notice] %></div>
          <% end %>

          <% if flash[:alert] %>
            <div class="alert alert-warning"><%= flash[:alert] %></div>
          <% end %>
        </div>
      </div>
 </div>
 <!-- left-bar -->
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-md-2">
        <div class="nav_left">
          <div class="sidebar-nav">
            <div class="navbar navbar-default" role="navigation">
              <div class="navbar-header">
                <span class="visible-xs navbar-brand">Sidebar menu</span>
              </div>
              <div class="navbar-collapse collapse sidebar-navbar-collapse">
                <ul class="nav navbar-nav" id="sidenav01">
                  <li>                  
                    <%= link_to products_path do %> 
                    <%=icon("info-sign")%> 產品管理
                    <% end %>
                  </li>                
                  <li>                  
                    <%= link_to orders_path do %> 
                    <%=icon("shopping-cart")%> 訂單管理
                    <% end %>
                  </li>
                  <li>                  
                    <%= link_to edit_about_path(:id) do %> 
                    <%=icon("hand-right")%> 關於我們
                    <% end %>
                  </li>
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </div><!--sidebar-nav-->
        </div>        
      </div>        
      <div class="col-xs-12 col-md-10">
         <%= yield %>
      </div>
    </div>
  </div><!-- /left bar -->
</div> <!-- /.main -->


</body>
</html>

app/views/layouts/simple.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inseason</title>
</head>
<body>
<% if Rails.env.prodcution? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  // ga('create', 'UA-145330-19', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

<%= yield %>
    
</body>
</html>